// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RNTtP-7Z_6JRdCQzBQbmaVeFtTJEhM4',
    appId: '1:876421964356:web:248d2890a1fc6c03509211',
    messagingSenderId: '876421964356',
    projectId: 'stemm-chat',
    authDomain: 'stemm-chat.firebaseapp.com',
    storageBucket: 'stemm-chat.firebasestorage.app',
    measurementId: 'G-DDWGNP12WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxgRksFgcoAS9qS0rmY4lAPWhnuWEwPM',
    appId: '1:876421964356:android:057341d511f3e92b509211',
    messagingSenderId: '876421964356',
    projectId: 'stemm-chat',
    storageBucket: 'stemm-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPvWCdWIyTBaNu8ZQdI5Wjk9xMsPxNuQ',
    appId: '1:876421964356:ios:8e9d001abccd281d509211',
    messagingSenderId: '876421964356',
    projectId: 'stemm-chat',
    storageBucket: 'stemm-chat.firebasestorage.app',
    iosBundleId: 'com.example.stemmChat',
  );

}